"""Build an ordered focused-audit image pack for pattern baseline v1.

Purpose
-------
Avoid manually searching the dataset. This script reads:
1) the full pattern_predictions.csv,
2) the focused audit CSV,
3) the per-instance visualizations already generated by run_pattern_baseline_v1_fixed.py,

and creates:
- a folder containing only the focused audit images, renamed in CSV row order;
- one contact sheet whose row numbers match the focused audit CSV.

Place this script at:
scripts/build_pattern_focus_audit_pack.py

Run from project root:
python scripts/build_pattern_focus_audit_pack.py
"""

from __future__ import annotations

import csv
import math
import shutil
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


PROJECT_ROOT = Path(__file__).resolve().parents[1]

REPORT_DIR = (
    PROJECT_ROOT
    / "reports"
    / "prd_attribute_extraction"
    / "pattern_v1"
)

OUTPUT_DIR = (
    PROJECT_ROOT
    / "outputs"
    / "prd_attribute_extraction"
    / "pattern_v1"
)

PREDICTIONS_CSV = REPORT_DIR / "pattern_predictions.csv"
FOCUS_CSV = REPORT_DIR / "pattern_manual_audit_focus_v1.csv"
PER_INSTANCE_DIR = OUTPUT_DIR / "per_instance"

FOCUS_OUT_DIR = OUTPUT_DIR / "focus_audit_v1"
CONTACT_SHEET = OUTPUT_DIR / "focus_audit_v1_contact_sheet.jpg"


def read_csv(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        raise FileNotFoundError(path)

    with path.open(
        "r",
        encoding="utf-8-sig",
        newline="",
    ) as f:
        return list(csv.DictReader(f))


def safe_name(text: str) -> str:
    return (
        text.replace("/", "_")
        .replace("\\", "_")
        .replace(":", "_")
    )


def main() -> None:
    predictions = read_csv(PREDICTIONS_CSV)
    focus_rows = read_csv(FOCUS_CSV)

    if not PER_INSTANCE_DIR.exists():
        raise FileNotFoundError(
            f"Missing per-instance folder: {PER_INSTANCE_DIR}"
        )

    # The original pattern script saves:
    # 001_<garment_id>.jpg, 002_<garment_id>.jpg, ...
    # using the same order as pattern_predictions.csv.
    prediction_index = {}

    for idx, row in enumerate(
        predictions,
        start=1,
    ):
        key = (
            row["source_image"].strip(),
            row["garment_id"].strip(),
        )
        prediction_index[key] = idx

    FOCUS_OUT_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    # Remove only old generated jpg copies in this focus folder.
    for old in FOCUS_OUT_DIR.glob("*.jpg"):
        old.unlink()

    panels = []
    missing = []

    for audit_idx, row in enumerate(
        focus_rows,
        start=1,
    ):
        key = (
            row["source_image"].strip(),
            row["garment_id"].strip(),
        )

        pred_idx = prediction_index.get(key)

        if pred_idx is None:
            missing.append(
                (
                    audit_idx,
                    row["garment_id"],
                    "not found in predictions",
                )
            )
            continue

        garment_id = row["garment_id"].strip()

        source_visual = (
            PER_INSTANCE_DIR
            / f"{pred_idx:03d}_{garment_id}.jpg"
        )

        if not source_visual.exists():
            missing.append(
                (
                    audit_idx,
                    garment_id,
                    str(source_visual),
                )
            )
            continue

        copied_name = (
            f"{audit_idx:02d}_"
            f"{safe_name(garment_id)}.jpg"
        )

        copied_path = (
            FOCUS_OUT_DIR
            / copied_name
        )

        shutil.copy2(
            source_visual,
            copied_path,
        )

        with Image.open(
            copied_path
        ) as img:
            img = img.convert("RGB")
            img.thumbnail(
                (360, 450)
            )

            panel = Image.new(
                "RGB",
                (400, 540),
                "white",
            )

            draw = ImageDraw.Draw(
                panel
            )
            font = ImageFont.load_default()

            title_lines = [
                (
                    f"ROW {audit_idx:02d} | "
                    f"{garment_id}"
                ),
                (
                    "pred: "
                    f"{row['predicted_pattern']}"
                ),
                (
                    "top2: "
                    f"{row['top2_pattern']}"
                ),
                (
                    "margin="
                    f"{float(row['top1_top2_margin']):.3f} "
                    "H="
                    f"{float(row['normalized_entropy']):.3f}"
                ),
                (
                    "reason: "
                    f"{row.get('audit_reason', '')}"
                ),
            ]

            y = 8

            for line in title_lines:
                draw.text(
                    (10, y),
                    line,
                    fill="black",
                    font=font,
                )
                y += 20

            x = (
                400 - img.width
            ) // 2

            image_y = 115

            panel.paste(
                img,
                (x, image_y),
            )

            panels.append(
                panel
            )

    if not panels:
        raise RuntimeError(
            "No focused audit images were created."
        )

    cols = 4
    rows = math.ceil(
        len(panels)
        / cols
    )

    sheet = Image.new(
        "RGB",
        (
            cols * 400,
            rows * 540,
        ),
        "white",
    )

    for idx, panel in enumerate(
        panels
    ):
        x = (
            idx % cols
        ) * 400
        y = (
            idx // cols
        ) * 540

        sheet.paste(
            panel,
            (x, y),
        )

    sheet.save(
        CONTACT_SHEET,
        quality=92,
    )

    print(
        "=== PATTERN FOCUS AUDIT PACK ==="
    )
    print(
        f"focus rows       : {len(focus_rows)}"
    )
    print(
        f"images created   : {len(panels)}"
    )
    print(
        f"missing          : {len(missing)}"
    )
    print(
        "folder           : "
        "outputs/prd_attribute_extraction/"
        "pattern_v1/focus_audit_v1/"
    )
    print(
        "contact sheet    : "
        "outputs/prd_attribute_extraction/"
        "pattern_v1/focus_audit_v1_contact_sheet.jpg"
    )

    if missing:
        print("")
        print("Missing rows:")
        for item in missing:
            print(item)

    print(
        "================================"
    )


if __name__ == "__main__":
    main()
