"""Test Mask2Former preprocessing with one DeepFashion2 sample.

This script converts one DeepFashion2 annotation into an instance
segmentation map and verifies the training inputs generated by the
Mask2Former image processor.
"""

import json
import logging
from pathlib import Path
from typing import Any

import cv2
import numpy as np
from PIL import Image
from transformers import AutoImageProcessor


LOGGER = logging.getLogger(__name__)

MODEL_NAME = "facebook/mask2former-swin-tiny-coco-instance"
DEEPFASHION2_CLASS_COUNT = 13


def load_annotation(annotation_path: Path) -> dict[str, Any]:
    """Load one DeepFashion2 annotation.

    Args:
        annotation_path: Path to the annotation JSON file.

    Returns:
        Parsed annotation dictionary.

    Raises:
        FileNotFoundError: If the annotation file does not exist.
    """
    if not annotation_path.is_file():
        raise FileNotFoundError(
            f"Annotation file not found: {annotation_path}"
        )

    with annotation_path.open("r", encoding="utf-8") as file:
        return json.load(file)


def get_item_index(item_name: str) -> int:
    """Extract the numeric index from an item name.

    Args:
        item_name: DeepFashion2 item key such as ``item1``.

    Returns:
        Numeric item index.

    Raises:
        ValueError: If the item name does not contain a valid index.
    """
    index_text = item_name.removeprefix("item")

    if not index_text.isdigit():
        raise ValueError(
            f"Invalid item name: {item_name}"
        )

    return int(index_text)


def create_binary_mask(
    segmentation: list[list[float]],
    image_height: int,
    image_width: int,
) -> np.ndarray:
    """Convert segmentation polygons into one binary mask.

    Args:
        segmentation: Flattened polygon coordinate lists.
        image_height: Original image height.
        image_width: Original image width.

    Returns:
        Binary mask containing values 0 and 1.
    """
    mask = np.zeros(
        (image_height, image_width),
        dtype=np.uint8,
    )

    for polygon in segmentation:
        if len(polygon) < 6 or len(polygon) % 2 != 0:
            continue

        points = np.asarray(
            polygon,
            dtype=np.float32,
        ).reshape(-1, 2)

        points[:, 0] = np.clip(
            points[:, 0],
            0,
            image_width - 1,
        )
        points[:, 1] = np.clip(
            points[:, 1],
            0,
            image_height - 1,
        )

        cv2.fillPoly(
            mask,
            [points.astype(np.int32)],
            1,
        )

    return mask


def create_instance_segmentation_map(
    annotation: dict[str, Any],
    image_height: int,
    image_width: int,
) -> tuple[np.ndarray, dict[int, int]]:
    """Create an instance map and instance-to-class mapping.

    Args:
        annotation: Parsed DeepFashion2 annotation.
        image_height: Original image height.
        image_width: Original image width.

    Returns:
        Instance segmentation map and mapping from instance IDs
        to zero-based DeepFashion2 class IDs.
    """
    instance_map = np.full(
        (image_height, image_width),
        fill_value=255,
        dtype=np.int32,
    )

    instance_id_to_class_id: dict[int, int] = {}

    items = [
        (item_name, item_data)
        for item_name, item_data in annotation.items()
        if item_name.startswith("item")
        and isinstance(item_data, dict)
    ]

    items.sort(
        key=lambda item: get_item_index(item[0])
    )

    for instance_id, (item_name, item_data) in enumerate(
        items,
        start=1,
    ):
        category_id = item_data.get("category_id")
        segmentation = item_data.get("segmentation")

        if not isinstance(category_id, int):
            continue

        if not 1 <= category_id <= DEEPFASHION2_CLASS_COUNT:
            raise ValueError(
                f"Invalid category_id {category_id} in {item_name}"
            )

        if not isinstance(segmentation, list):
            continue

        binary_mask = create_binary_mask(
            segmentation,
            image_height,
            image_width,
        )

        overlap = (
            (instance_map != 255)
            & (binary_mask > 0)
        )

        overlap_count = int(
            np.count_nonzero(overlap)
        )

        if overlap_count > 0:
            LOGGER.warning(
                "%s overlaps existing instances by %d pixels",
                item_name,
                overlap_count,
            )

        instance_map[binary_mask > 0] = instance_id

        instance_id_to_class_id[
            instance_id
        ] = category_id - 1

    return (
        instance_map,
        instance_id_to_class_id,
    )


def configure_logging() -> None:
    """Configure console logging."""
    logging.basicConfig(
        level=logging.INFO,
        format="%(levelname)s: %(message)s",
    )


def main() -> None:
    """Verify one Mask2Former training input."""
    configure_logging()

    project_root = Path(__file__).resolve().parents[1]

    image_path = (
        project_root.parent
        / "fashion_data"
        / "raw"
        / "train"
        / "train"
        / "image"
        / "000001.jpg"
    )

    annotation_path = (
        project_root.parent
        / "fashion_data"
        / "raw"
        / "train"
        / "train"
        / "annos"
        / "000001.json"
    )

    image = Image.open(
        image_path
    ).convert("RGB")

    annotation = load_annotation(
        annotation_path
    )

    (
        instance_map,
        instance_id_to_class_id,
    ) = create_instance_segmentation_map(
        annotation,
        image.height,
        image.width,
    )

    LOGGER.info(
        "Instance IDs: %s",
        np.unique(instance_map).tolist(),
    )

    LOGGER.info(
        "Instance-to-class mapping: %s",
        instance_id_to_class_id,
    )

    processor = AutoImageProcessor.from_pretrained(
        MODEL_NAME,
        use_fast=False,
    )

    inputs = processor(
        images=image,
        segmentation_maps=instance_map,
        instance_id_to_semantic_id=instance_id_to_class_id,
        ignore_index=255,
        do_reduce_labels=False,
        return_tensors="pt",
    )

    class_labels = inputs["class_labels"][0]
    mask_labels = inputs["mask_labels"][0]

    LOGGER.info(
        "Pixel values shape: %s",
        tuple(inputs["pixel_values"].shape),
    )

    LOGGER.info(
        "Class labels: %s",
        class_labels.tolist(),
    )

    LOGGER.info(
        "Mask labels shape: %s",
        tuple(mask_labels.shape),
    )

    LOGGER.info(
        "Mask values: %s",
        mask_labels.unique().tolist(),
    )


if __name__ == "__main__":
    main()